### ISSUE TITLE
Log in screen scrolls down (can't see what I'm typing)

### ISSUE THREAD

**Issue by nazaradeh** [nick-delirium/lemmy-fennec#32] opened 2023-07-24 16:43 UTC
Version 0.1.1

When I go to type in the lemmy instance, it scrolls down and I can't see what I'm typing. It does not let me scroll back up while my keyboard is active and trying to type.

Sidenote: after clicking connect on the instance, it doesnt provide any feedback. It doesn't say whether or not it has connected to said onstance.

**Comment by nick-delirium** [comment] 2023-07-26 11:43
Can you please send me a video or a screenshot of that issue so I'll be able to fix it faster

**Comment by nazaradeh** [comment] 2023-07-29 01:34
https://github.com/nick-delirium/lemmy-fennec/assets/36654763/104f0aad-efaa-4eb3-88e9-aabc84b361eb

**Comment by nazaradeh** [comment] 2023-07-29 01:35
https://github.com/nick-delirium/lemmy-fennec/assets/36654763/48e28315-9b19-4f81-928a-99a43fc6f8c3

**Comment by nick-delirium** [comment] 2023-07-30 12:47
Should be fixed in b48320f

**Comment by nick-delirium** [comment] 2023-07-31 12:57
@nazaradeh pls test if the issue is resolved in [0.1.3](https://github.com/nick-delirium/lemmy-fennec/releases/tag/0.1.3)

**Comment by nazaradeh** [comment] 2023-08-03 21:58
@nick-delirium yes it is resolved :)

**Closed as completed** 2023-08-04 08:19 UTC
